_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 71
            "2":
                - 1
                - 11
                - 49
                - 71
            "3":
                - 13
                - 16
                - 55
                - 61
            "4": 3.12.9
            "5": 0.20.1
            "6": 4.51.3
            "8":
                - 3
            "12": 0.20.1
            "13": windows-amd64
model_args:
    value:
        bias: false
        block_size: 512
        decoder_start_token_id: 0
        dropout: 0.1
        eos_token_id: 3
        head_dim: 64
        n_embd: 512
        n_head: 8
        n_layer: 6
        pad_token_id: 0
        q_rank: 8
        rank: 4
        using_groupnorm: true
        vocab_size: 7110
optimizer_args:
    value:
        beta1: 0.9
        beta2: 0.999
        decay_lr: true
        grad_clip: 0.9
        learning_rate: 0.0001
        min_lr: 1e-06
        optimizer_name: adamw
        schedule: cosine
        warmup_iters: 2000
        weight_decay: 0.01
training_args:
    value:
        batch_size: 1
        eval_interval: 1
        eval_iters: 1
        gradient_accumulation_steps: 1
        log_interval: 1
        lr_decay_iters: 50000
        max_iters: 2
        max_source_length: 512
        max_target_length: 256
